spring:
  config: 
    import: "optional:file:.env[.properties]"

  application:
    name: gateway

  threads:
    virtual:
      enabled: ${SPRING_THREADS_VIRTUAL_ENABLED:false}
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/gateway_db}
    username: ${SPRING_R2DBC_USERNAME:myuser}
    password: ${SPRING_R2DBC_PASSWORD:mypassword}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379

  sql:
    init:
        mode: always