spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user-service-auth
          uri: ${USER_SERVICE_URI:http://localhost:8001}
          predicates:
            - Path=/api/v1/auth/**
        - id: user-service-users
          uri: ${USER_SERVICE_URI:http://localhost:8001}
          predicates:
            - Path=/api/v1/users/**
        - id: threads-service
          uri: ${THREADS_SERVICE_URI:http://localhost:8002}
          predicates:
            - Path=/api/v1/threads/**
        - id: voting-service
          uri: ${VOTING_SERVICE_URI:http://localhost:8003}
          predicates:
            - Path=/api/v1/votes/**
        - id: user-service-health
          uri: ${USER_SERVICE_URI:http://localhost:8001}
          predicates:
            - Path=/health

jwt:
  secret: ${JWT_SECRET_KEY}
