spring:
  application:
    name: gateway
  data:
    redis:
      host: ${REDIS_HOST:redis-cache}
      port: ${REDIS_PORT:6379}

  cloud:
    gateway:
      routes:
        - id: user-service-auth
          uri: ${USER_SERVICE_URI:http://user-service:8000}
          predicates:
            - Path=/api/v1/auth/**
        - id: user-service-users
          uri: ${USER_SERVICE_URI:http://user-service:8000}
          predicates:
            - Path=/api/v1/users/**
        - id: threads-service
          uri: ${THREADS_SERVICE_URI:http://threads:8000}
          predicates:
            - Path=/api/v1/threads/**
        - id: voting-service
          uri: ${VOTING_SERVICE_URI:http://voting:8000}
          predicates:
            - Path=/api/v1/votes/**
        - id: moderation-service
          uri: ${MODERATION_SERVICE_URI:http://moderation-service:8000}
          predicates:
            - Path=/api/v1/moderation/**
        - id: expert-review-service
          uri: ${EXPERT_REVIEW_SERVICE_URI:http://expert-review-service:8000}
          predicates:
            - Path=/api/v1/reviews/**
        - id: user-service-health
          uri: ${USER_SERVICE_URI:http://user-service:8000}
          predicates:
            - Path=/health

jwt:
  secret: ${JWT_SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://jaeger:4317}
logging:
  level:
    org.springframework.security: DEBUG
